/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EndGameCard: typeof import('./src/components/EndGameCard.vue')['default']
    GameHeader: typeof import('./src/components/GameHeader.vue')['default']
    IHeroiconsArrowPath: typeof import('~icons/heroicons/arrow-path')['default']
    IHeroiconsChevronDown: typeof import('~icons/heroicons/chevron-down')['default']
    IHeroiconsChevronUp: typeof import('~icons/heroicons/chevron-up')['default']
    IHeroiconsUser: typeof import('~icons/heroicons/user')['default']
    IHeroiconsXMark: typeof import('~icons/heroicons/x-mark')['default']
    InfoCardWithActions: typeof import('./src/components/InfoCardWithActions.vue')['default']
    PlayerTH: typeof import('./src/components/PlayerTH.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreTable: typeof import('./src/components/ScoreTable.vue')['default']
    ShotButtons: typeof import('./src/components/ShotButtons.vue')['default']
    ShotTD: typeof import('./src/components/ShotTD.vue')['default']
  }
}
